import type { Metadata } from "next";
import FunnelBeacon from "@/app/components/seo/FunnelBeacon";
import PageBody from "@/app/components/seo/PageBody";

const BASE = process.env.NEXT_PUBLIC_APP_URL || "https://cv.rabit.sa";

export const metadata: Metadata = {
  title: "PDF Resume Readability Checker — Free ATS Text Test | Sira",
  description: "Upload your resume PDF or Word file and see exactly what text an ATS extracts from it. Free, no signup — catches scanned images and broken layouts before a recruiter does.",
  alternates: {
    canonical: `${BASE}/pdf-readability-checker`,
    languages: { en: `${BASE}/pdf-readability-checker`, ar: `${BASE}/ar/pdf-readability-checker`, "x-default": `${BASE}/pdf-readability-checker` },
  },
};

export default function PdfReadabilityCheckerLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      {children}
      <PageBody
        heading="Why a resume that looks fine can still fail"
        intro={[
          "A human opens your PDF and sees a page. An applicant tracking system does something completely different: it runs a text extractor over the file and works only with whatever comes out. If that extractor returns a blank page, three words, or one giant run-on line with no breaks, the system never sees your experience — no matter how well the file is designed.",
          "This happens most often with resumes exported as flattened images (common from some design tools and phone-scanned documents), heavy use of text boxes or multi-column tables, and PDFs generated by software that embeds text in a non-standard order. None of these are visible problems to a human reader, which is exactly why they go unnoticed until an application goes nowhere.",
          "This tool runs the same text-extraction step this product's own resume builder uses on an import, so the result you see here is not a guess — it is what actually happens to your file.",
        ]}
        stepsHeading="How to use it"
        steps={[
          { title: "Upload your file", body: "PDF or Word, up to 5MB. Nothing is saved on our servers — only the extracted text is shown to you, in your browser." },
          { title: "Read the verdict", body: "Readable, partially readable, or not readable — based on how much text came out and whether its structure (line breaks) survived." },
          { title: "Check the preview", body: "The extracted text is shown exactly as a screening system would see it. If a section is missing or jumbled here, it is missing or jumbled for every system that reads this file." },
          { title: "Rebuild if needed", body: "A layout problem in an existing file usually isn't worth patching — starting fresh in a text-based template avoids the whole category of issue." },
        ]}
        faqHeading="Questions people actually ask"
        faq={[
          {
            q: "My resume looks perfect when I open it — why would it fail this test?",
            a: "Because you're reading it with your eyes, not extracting its text programmatically. A scanned image, a text box, or an oddly-encoded PDF can look flawless on screen while returning nothing (or the wrong order) to a text extractor.",
          },
          {
            q: "What should I do if my file comes back 'not readable'?",
            a: "Don't try to fix the existing PDF — most of the time the problem is baked into how it was created. Rebuild the content in a text-based template instead of an image-based or heavily-designed one.",
          },
          {
            q: "Is a Word (.docx) file safer than a PDF?",
            a: "Usually, yes — a .docx is closer to plain text by construction. But a Word file built from text boxes or an imported image has the exact same problem, so the safest move is checking either format rather than assuming.",
          },
          {
            q: "Does this check my resume's content or wording?",
            a: "No — this tool only checks whether text can be extracted from the file at all. For content, keyword match, and wording against a specific job, use the ATS resume checker instead.",
          },
          {
            q: "Is my file stored anywhere?",
            a: "No. The file is sent once to extract its text and is not saved. Nothing about its content appears in a URL or in analytics.",
          },
        ]}
        relatedHeading="Related"
        related={[
          { href: "/optimize", label: "Check my resume" },
          { href: "/builder", label: "Build my resume" },
          { href: "/templates", label: "ATS-safe templates" },
          { href: "/ar/pdf-readability-checker", label: "فحص قابلية قراءة ملفك بالعربية" },
        ]}
      />
      <FunnelBeacon step="toolOpened" />
    </>
  );
}
